seed: 42
teacher: math_repl/models/student_clean/final
tokenizer: math_repl/models/student_clean/final
teacher_cfg: null
is_teacher: false
lam: 0.0
wandb_lam: 1.0e-08
antidistillation: false
eps: 0.01
proxy_student: Qwen/Qwen2.5-3B
grad_path: null
data_split: hendrycks_math_test
max_samples: 500
batch_size: 32
max_length: 2048
max_prompt_length: 1024
tau: 0.0
answer_force: true
use_wandb: false
exp_dir: math_repl
metadata_dir: math_repl/metadata
trace_registry: math_repl/metadata/trace_registry.jsonl
trace_dir: math_repl/traces
trace_name: eval_train_clean
trace_path: math_repl/traces/eval_train_clean
trace_colname: trace
repetition_penalty: 1.0
hydra:
  run_dir: math_repl/metadata/{now:yyyy-MM-dd_HH-mm-ss}
  job_name: gentraces
  cwd: /antidistillation-sampling
stats:
  raw_accuracy: 0.108
  af_accuracy: 0.166
  trace_len_stats:
    count: 500.0
    mean: 1490.256
    std: 560.6914090445409
    min: 287.0
    25%: 1115.25
    50%: 1727.0
    75%: 1972.25
    max: 2049.0
