seed: 0
teacher: Qwen/Qwen2.5-3B-Instruct
tokenizer: Qwen/Qwen2.5-3B-Instruct
teacher_cfg: null
is_teacher: true
lam: 0
wandb_lam: 1.0e-08
antidistillation: false
eps: 0.01
proxy_student: Qwen/Qwen2.5-3B
grad_path: null
repetition_penalty: 1.0
data_split: gsm8k_holdout
max_samples: 200
batch_size: 4
max_length: 1024
max_prompt_length: 512
tau: 0.6
answer_force: true
use_wandb: false
exp_dir: traj_static
metadata_dir: traj_static/metadata
trace_registry: traj_static/metadata/trace_registry.jsonl
trace_dir: traj_static/traces
trace_name: holdout_3b
trace_path: traj_static/traces/holdout
trace_colname: trace
hydra:
  run_dir: traj_static/metadata/{now:yyyy-MM-dd_HH-mm-ss}
  job_name: gentraces
  cwd: /root/antidistillation-sampling
stats:
  raw_accuracy: 0.905
  af_accuracy: 0.905
  trace_len_stats:
    count: 200.0
    mean: 426.525
    std: 104.14427263471124
    min: 216.0
    25%: 356.0
    50%: 414.0
    75%: 484.0
    max: 949.0
